// Generated by https://quicktype.io

export interface ConfigInterface {
	siteName: string;
	site: string;
	sofwareName: string;
	logo: string;
	icons: Icons;
	menu: Menu[];
	leftMenu: LeftMenu[];
	themes: Themes;
}

export interface Icons {
	help: string;
	close: string;
	open: string;
}

export interface LeftMenu {
	id: number;
	name: string;
	active: boolean;
	url: string;
	icon: string;
}

export interface Menu {
	id: number;
	name: string;
	active: boolean;
}

export interface Themes {
	default: Clear;
	clear: Clear;
	dark: Clear;
}

export interface Clear {
	color: string;
	backgroundColor: string;
	headerBackground: string;
	headerColor: string;
	leftMenuBackground: string;
	leftMenuColor: string;
	active?: boolean;
	buttonInfoColor?: string;
	buttonInfoBackground?: string;
}
